#include "pch.h"
#include "global.h"

tTransform g_transform = {};
tGlobal GlobalData = {};



extern const char* RES_TYPE_STR[(UINT)RES_TYPE::END] =
{
	"MESHDATA",
	"MATERIAL",
	"PREFAB",
	"MESH",
	"TEXTURE",
	"SOUND",
	"GRAPHICS_SHADER",
	"COMPUTE_SHADER"
};

extern const wchar_t* RES_TYPE_WSTR[(UINT)RES_TYPE::END] =
{
	L"MESHDATA",
	L"MATERIAL",
	L"PREFAB",
	L"MESH",
	L"TEXTURE",
	L"SOUND",
	L"GRAPHICS_SHADER",
	L"COMPUTE_SHADER"
};



extern const char* COMPONENT_TYPE_STR[(UINT)COMPONENT_TYPE::END] =
{
	"TRANSFORM",
	"COLLIDER2D",
	"COLLIDER3D",
	"EQUIP",
	"ANIMATOR2D",
	"ANIMATOR3D",
	"MOTIONBLUR",
	"LIGHT2D",
	"LIGHT3D",
	"RIGIDBODY",
	"PXRIGIDBODY",
	"NAVMESH",
	"CAMERA",

	"MESHRENDER",
	"PARTICLESYSTEM",
	"TILEMAP",
	"LANDSCAPE",
	"SKYBOX",
	"DECAL",
};

extern const wchar_t* COMPONENT_TYPE_WSTR[(UINT)COMPONENT_TYPE::END] =
{
	L"TRANSFORM",
	L"COLLIDER2D",
	L"COLLIDER3D",
	L"EQUIP",
	L"ANIMATOR2D",
	L"ANIMATOR3D",
	L"MOTIONBLUR",
	L"LIGHT2D",
	L"LIGHT3D",
	L"RIGIDBODY",
	L"PXRIGIDBODY",
	L"NAVMESH",
	L"CAMERA",
	L"MESHRENDER",
	L"PARTICLESYSTEM",
	L"TILEMAP",
	L"LANDSCAPE",
	L"SKYBOX",
	L"DECAL",
};